ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.ssv_guardian_trap_poc]
path = "out/SSVGuardianTrap.sol/SSVGuardianTrap.json"
response_contract = "0x73156FD92B4e813233Af451E7d6359E17493c7c3"
response_function = "executeResponse(bytes)"
cooldown_period_blocks = 33
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size = 10
private_trap = true
whitelist = ["0x87358cb0cba4380393cc512b796775116b7ddc20"]
address = "0x2580671CB93484a6279FA8E5700148Efb34Be989"
